<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OdyToolsStandaloneDefine>DLG_STANDALONE</OdyToolsStandaloneDefine>
    <OdyToolsStandaloneStartupObject>OdyTools.Editors.Standalone.DLG.Program</OdyToolsStandaloneStartupObject>
    <OdyToolsStandaloneBioWareRef>..\..\..\..\BioWare</OdyToolsStandaloneBioWareRef>
    <OdyToolsStandaloneAppConfig>$(MSBuildProjectDirectory)\..\app.config</OdyToolsStandaloneAppConfig>
    <_OdyToolsRoot>$([System.IO.Path]::GetDirectoryName($([System.IO.Path]::GetDirectoryName('$(MSBuildProjectDirectory)'))))</_OdyToolsRoot>
  </PropertyGroup>
  <Import Project="..\Standalone\OdyTools.Standalone.Editor.props" />
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Windows.Extensions" Version="10.0.1" Condition="'$(TargetFramework)' != 'net48'" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.DLG.Standalone.cs" />
    <Compile Include="..\Standalone\EditorStandaloneHost\EditorStandaloneProgram.cs" />
    <Compile Include="..\Standalone\EditorStandaloneHost\EditorStandaloneApp.axaml.cs" />
    <Compile Include="OdyToolDLG.axaml.cs" />
    <Compile Include="DLGSettings.cs" />
    <Compile Include="TwoDAFileHelper.cs" />
    <Compile Include="DLGModel.cs" />
    <Compile Include="DLGConstants.cs" />
    <Compile Include="DLGNodeTypes.cs" />
    <Compile Include="DLGListWidget.cs" />
    <Compile Include="DLGListWidgetItem.cs" />
    <Compile Include="DLGStandardItem.cs" />
    <Compile Include="DlgGraphScene.cs" />
    <Compile Include="DlgGraphColors.cs" />
    <Compile Include="DlgTreeItemView.cs" />
    <Compile Include="DLGActionHistory.cs" />
    <Compile Include="DLGDebugUtils.cs" />
    <Compile Include="IDLGAction.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Editor.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\EditorHelpers.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\EditorWikiMapping.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\WindowUtils.cs" />
    <Compile Include="$(_OdyToolsRoot)\Data\OdyInstallation.cs" />
    <Compile Include="$(_OdyToolsRoot)\Data\Settings.cs" />
    <Compile Include="$(_OdyToolsRoot)\Data\IEditorInstallationSettings.cs" />
    <Compile Include="$(_OdyToolsRoot)\Data\GlobalSettings.cs" />
    <Compile Include="$(_OdyToolsRoot)\Common\Localization.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\InlineEditorHelp.cs" />
    <Compile Include="$(_OdyToolsRoot)\Utils\PathUtils.cs" />
    <Compile Include="$(_OdyToolsRoot)\Common\CollectionViewSource.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\EditorHelpDialog.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\ReferenceChooserDialog.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\ColorPickerDialog.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\LocalizedStringDialog.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\EditorInstallationSettingsDialogBase.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\DLGSettingsDialog.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Widgets\Settings\InstallationsWidget.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\Edit\DialogAnimationDialog.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\LoadFromLocationResultDialog.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\Edit\DialogModelDialog.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Actions\AddRootNodeAction.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Actions\AddChildToItemAction.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Actions\AddStarterAction.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Actions\MoveStarterAction.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Actions\RemoveStarterAction.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Actions\RemoveLinkAction.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Actions\AddStuntAction.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Actions\RemoveStuntAction.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Actions\EditStuntAction.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Actions\PasteItemAction.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Actions\DeleteNodeEverywhereAction.cs" />
    <Compile Include="$(_OdyToolsRoot)\Editors\Actions\RestoreOrphanAction.cs" />
    <Compile Include="..\..\Widgets\IMediaPlayer.cs" />
    <Compile Include="..\..\Widgets\NAudioMediaPlayer.cs" />
    <Compile Include="$(_OdyToolsRoot)\Widgets\Edit\ComboBox2DA.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Widgets\Edit\PlainTextEdit.cs" />
    <Compile Include="$(_OdyToolsRoot)\Widgets\Edit\GFFFieldSpinBox.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Widgets\Edit\ColorEdit.axaml.cs" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaXaml Remove="**\*.axaml" />
    <AvaloniaXaml Include="..\Standalone\EditorStandaloneHost\EditorStandaloneApp.axaml" Link="EditorStandaloneHost/EditorStandaloneApp.axaml" />
    <AvaloniaXaml Include="OdyToolDLG.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Dialogs\EditorHelpDialog.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Dialogs\ColorPickerDialog.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Dialogs\LocalizedStringDialog.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Dialogs\DLGSettingsDialog.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Widgets\Settings\InstallationsWidget.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Dialogs\Edit\DialogAnimationDialog.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Dialogs\Edit\DialogModelDialog.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Widgets\Edit\ComboBox2DA.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Widgets\Edit\GFFFieldSpinBox.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Widgets\Edit\ColorEdit.axaml" />
  </ItemGroup>
</Project>
