<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OdyToolsStandaloneDefine>ARE_STANDALONE</OdyToolsStandaloneDefine>
    <_OdyToolsRoot>$([System.IO.Path]::GetDirectoryName('$(MSBuildProjectDirectory)'))</_OdyToolsRoot>
  </PropertyGroup>
  <Import Project="Standalone\OdyTools.Standalone.Editor.props" />
  <ItemGroup>
    <Compile Include="Standalone\EditorStandaloneHost\EditorStandaloneProgram.cs" />
    <Compile Include="Standalone\EditorStandaloneHost\EditorStandaloneApp.axaml.cs" />
    <Compile Include="OdyToolARE.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Widgets\Edit\ColorEdit.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Widgets\LocalizedStringEdit.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\ColorPickerDialog.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\LocalizedStringDialog.axaml.cs" />
    <Compile Include="Editor.cs" />
    <Compile Include="EditorHelpers.cs" />
    <Compile Include="EditorWikiMapping.cs" />
    <Compile Include="WindowUtils.cs" />
    <Compile Include="$(_OdyToolsRoot)\Common\CollectionViewSource.cs" />
    <Compile Include="$(_OdyToolsRoot)\Data\OdyInstallation.cs" />
    <Compile Include="$(_OdyToolsRoot)\Data\Settings.cs" />
    <Compile Include="$(_OdyToolsRoot)\Data\IEditorInstallationSettings.cs" />
    <Compile Include="$(_OdyToolsRoot)\Data\GlobalSettings.cs" />
    <Compile Include="$(_OdyToolsRoot)\Utils\PathUtils.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\EditorHelpDialog.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\InlineEditorHelp.cs" />
    <Compile Include="$(_OdyToolsRoot)\Dialogs\EditorInstallationSettingsDialogBase.cs" />
    <Compile Include="$(_OdyToolsRoot)\Widgets\Settings\InstallationsWidget.axaml.cs" />
    <Compile Include="$(_OdyToolsRoot)\Common\Localization.cs" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaXaml Remove="**\*.axaml" />
    <AvaloniaXaml Remove="*OdyTool*.axaml" />
    <AvaloniaXaml Include="Standalone\EditorStandaloneHost\EditorStandaloneApp.axaml" Link="EditorStandaloneHost/EditorStandaloneApp.axaml" />
    <AvaloniaXaml Include="OdyToolARE.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Dialogs\EditorHelpDialog.axaml" Link="Dialogs/EditorHelpDialog.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Widgets\Edit\ColorEdit.axaml" Link="Widgets/Edit/ColorEdit.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Widgets\LocalizedStringEdit.axaml" Link="Widgets/LocalizedStringEdit.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Dialogs\ColorPickerDialog.axaml" Link="Dialogs/ColorPickerDialog.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Dialogs\LocalizedStringDialog.axaml" Link="Dialogs/LocalizedStringDialog.axaml" />
    <AvaloniaXaml Include="$(_OdyToolsRoot)\Widgets\Settings\InstallationsWidget.axaml" Link="Widgets/Settings/InstallationsWidget.axaml" />
  </ItemGroup>
</Project>
