using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using BioWare.TSLPatcher.Mods;

namespace OdyTools.Shell
{
    internal static class ShellDiffService
    {
        public static string BuildDiffPatch(string target1Path, string target2Path)
        {
            if (string.IsNullOrWhiteSpace(target1Path) || !Directory.Exists(target1Path))
            {
                throw new DirectoryNotFoundException($"Diff target 1 was not found: {target1Path}");
            }
            if (string.IsNullOrWhiteSpace(target2Path) || !Directory.Exists(target2Path))
            {
                throw new DirectoryNotFoundException($"Diff target 2 was not found: {target2Path}");
            }

            string outputRoot = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "Andastra",
                "OdyTools",
                "DiffPatches",
                DateTimeOffset.UtcNow.ToString("yyyyMMdd_HHmmss"));
            string tslPatchDataPath = Path.Combine(outputRoot, "tslpatchdata");
            Directory.CreateDirectory(tslPatchDataPath);

            var files1 = Directory.GetFiles(target1Path, "*", SearchOption.AllDirectories)
                .ToDictionary(path => GetRelativePath(target1Path, path), StringComparer.OrdinalIgnoreCase);
            var files2 = Directory.GetFiles(target2Path, "*", SearchOption.AllDirectories)
                .ToDictionary(path => GetRelativePath(target2Path, path), StringComparer.OrdinalIgnoreCase);

            var installFiles = new List<InstallFile>();

            foreach (var pair in files2)
            {
                string relativePath = pair.Key;
                string source2 = pair.Value;
                bool changed = !files1.TryGetValue(relativePath, out string source1) || !AreFilesEqual(source1, source2);
                if (!changed)
                {
                    continue;
                }

                string destinationPath = Path.Combine(tslPatchDataPath, relativePath);
                Directory.CreateDirectory(Path.GetDirectoryName(destinationPath) ?? tslPatchDataPath);
                File.Copy(source2, destinationPath, overwrite: true);

                string destinationFolder = Path.GetDirectoryName(relativePath);
                if (string.IsNullOrWhiteSpace(destinationFolder))
                {
                    destinationFolder = "Override";
                }

                installFiles.Add(new InstallFile(Path.GetFileName(relativePath), replaceExisting: true, destination: destinationFolder));
            }

            var serializer = new TSLPatcherINISerializer();
            var modifications = ModificationsByType.CreateEmpty();
            modifications.Install.AddRange(installFiles);
            string ini = serializer.Serialize(modifications, includeHeader: true, includeSettings: true, verbose: true);
            File.WriteAllText(Path.Combine(tslPatchDataPath, "changes.ini"), ini);

            File.WriteAllText(
                Path.Combine(outputRoot, "README.txt"),
                "Generated by OdyTools shell diff workflow.\n" +
                $"Target 1: {target1Path}\n" +
                $"Target 2: {target2Path}\n" +
                $"Changed files packaged: {installFiles.Count}\n");

            return tslPatchDataPath;
        }

        private static string GetRelativePath(string basePath, string path)
        {
#if NET472 || NET48
            var baseUri = new Uri(Path.GetFullPath(basePath).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar) + Path.DirectorySeparatorChar);
            var pathUri = new Uri(Path.GetFullPath(path));
            return Uri.UnescapeDataString(baseUri.MakeRelativeUri(pathUri).ToString().Replace('/', Path.DirectorySeparatorChar));
#else
            return Path.GetRelativePath(basePath, path);
#endif
        }

        private static bool AreFilesEqual(string file1, string file2)
        {
            var info1 = new FileInfo(file1);
            var info2 = new FileInfo(file2);
            if (info1.Length != info2.Length)
            {
                return false;
            }

            using (var hash = SHA256.Create())
            {
                byte[] h1 = hash.ComputeHash(File.ReadAllBytes(file1));
                byte[] h2 = hash.ComputeHash(File.ReadAllBytes(file2));
                return h1.SequenceEqual(h2);
            }
        }
    }
}
