# Ghidra script: Bulk rename TSL ExecuteCommand handlers using K1 command ID mapping
# Run this in AgentDecompile execute-script on /TSL_GOG_swkotor2
#
# This script:
# 1. Decompiles TSL's InitializeCommands @ 0x0077b530
# 2. Extracts command ID -> handler address mapping
# 3. Cross-references with K1's known command ID -> name mapping
# 4. Renames ~700 unnamed FUN_ functions to their K1 equivalents
#
# Prerequisites: AgentDecompile MCP server must be running with TSL program loaded
from __future__ import annotations

import re

from ghidra.app.decompiler import DecompileOptions, DecompInterface
from ghidra.framework.project import DefaultProject, DefaultProjectManager, ProjectDataService
from ghidra.program.model.listing import FunctionManager, Program
from ghidra.program.model.symbol import SourceType
from ghidra.util.task import ConsoleTaskMonitor

activeProject = DefaultProjectManager().getActiveProject()
projectData = activeProject.getProjectData()
currentProgram = projectData.getCurrentProgram()

fm = currentProgram.getFunctionManager()
af = currentProgram.getAddressFactory()

# Phase 1: Decompile TSL InitializeCommands to get command table
func = fm.getFunctionAt(af.getAddress("0x0077b530"))
if func is None:
    raise Exception("InitializeCommands not found at 0x0077b530")

decomp = DecompInterface()
opts = DecompileOptions()
opts.setMaxPayloadMBytes(256)
decomp.setOptions(opts)
decomp.openProgram(currentProgram)

results = decomp.decompileFunction(func, 600, ConsoleTaskMonitor())
if not results.decompileCompleted():
    decomp.dispose()
    raise Exception("Decompilation failed: %s" % results.getErrorMessage())

code = results.getDecompiledFunction().getC()
decomp.dispose()

# Parse TSL table assignments:
# Pattern: *(code **)(*(int *)(this + 0xc) + OFFSET) = HANDLER;
pattern = re.compile(r"\*\(code \*\*\)\(\*\(int \*\)\(this \+ 0xc\) \+ (0x[0-9a-f]+)\) = (\w+);")
tsl_table = {}  # cmd_id -> handler_name
for offset_str, handler in pattern.findall(code):
    cmd_id = int(offset_str, 16) // 4
    tsl_table[cmd_id] = handler

# Build reverse map: handler_name -> [cmd_ids]
tsl_handler_to_ids = {}
for cmd_id, handler in tsl_table.items():
    if handler not in tsl_handler_to_ids:
        tsl_handler_to_ids[handler] = []
    tsl_handler_to_ids[handler].append(cmd_id)

# Phase 2: K1 command ID -> handler name mapping (extracted from K1 InitializeCommands @ 0x0054c960)
k1 = {
    1: "ExecuteCommandPrintString",
    2: "ExecuteCommandPrintFloat",
    3: "ExecuteCommandFloatToString",
    4: "ExecuteCommandPrintInteger",
    5: "ExecuteCommandPrintObject",
    6: "ExecuteCommandAssignCommand",
    7: "ExecuteCommandDelayCommand",
    8: "ExecuteCommandExecuteScript",
    9: "ExecuteCommandClearAllActions",
    10: "ExecuteCommandSetFacing",
    11: "ExecuteCommandSwitchPlayerCharacter",
    12: "ExecuteCommandSetTime",
    13: "ExecuteCommandSetPartyLeader",
    14: "ExecuteCommandSetAreaUnescapable",
    15: "ExecuteCommandGetAreaUnescapable",
    16: "ExecuteCommandGetTimeHour",
    17: "ExecuteCommandGetTimeMinute",
    18: "ExecuteCommandGetTimeSecond",
    19: "ExecuteCommandGetTimeMillisecond",
    20: "ExecuteCommandActionRandomWalk",
    21: "ExecuteCommandMoveToPoint",
    22: "ExecuteCommandMoveToObject",
    23: "ExecuteCommandActionMoveAwayFromObject",
    24: "ExecuteCommandGetArea",
    25: "ExecuteCommandGetEnteringObject",
    26: "ExecuteCommandGetExitingObject",
    27: "ExecuteCommandGetPosition",
    28: "ExecuteCommandGetFacing",
    29: "ExecuteCommandGetItemPossessor",
    30: "ExecuteCommandGetItemPossessedBy",
    31: "ExecuteCommandCreateItemOnObject",
    32: "ExecuteCommandActionEquipItem",
    33: "ExecuteCommandActionUnequipItem",
    34: "ExecuteCommandActionPickUpItem",
    35: "ExecuteCommandActionPutDownItem",
    36: "ExecuteCommandGetLastAttacker",
    37: "ExecuteCommandAttack",
    38: "ExecuteCommandGetNearestObject",
    39: "ExecuteCommandSpeakString",
    40: "ExecuteCommandPlayAnimation",
    41: "ExecuteCommandGetDistanceToObject",
    42: "ExecuteCommandGetIsObjectValid",
    43: "ExecuteCommandActionOpenDoor",
    44: "ExecuteCommandActionCloseDoor",
    45: "ExecuteCommandSetCameraFacing",
    46: "ExecuteCommandPlaySound",
    47: "ExecuteCommandGetSpellTargetObject",
    48: "ExecuteCommandCastSpell",
    49: "ExecuteCommandGetHitpoints",
    50: "ExecuteCommandGetHitpoints",
    51: "ExecuteCommandEffectComplex",
    52: "ExecuteCommandModuleAccess",
    53: "ExecuteCommandGetSubScreenID",
    54: "ExecuteCommandCancelCombat",
    55: "ExecuteCommandGetCurrentForcePoints",
    56: "ExecuteCommandGetMaxForcePoints",
    57: "ExecuteCommandPauseGame",
    58: "ExecuteCommandSetRestrictMode",
    59: "ExecuteCommandGetStringLength",
    60: "ExecuteCommandGetStringUpperCase",
    61: "ExecuteCommandGetStringLowerCase",
    62: "ExecuteCommandGetStringRight",
    63: "ExecuteCommandGetStringLeft",
    64: "ExecuteCommandInsertString",
    65: "ExecuteCommandGetSubString",
    66: "ExecuteCommandFindSubString",
    67: "ExecuteCommandMath",
    68: "ExecuteCommandMath",
    69: "ExecuteCommandMath",
    70: "ExecuteCommandMath",
    71: "ExecuteCommandMath",
    72: "ExecuteCommandMath",
    73: "ExecuteCommandMath",
    74: "ExecuteCommandMath",
    75: "ExecuteCommandMath",
    76: "ExecuteCommandMath",
    77: "ExecuteCommandMath",
    78: "ExecuteCommandEffectHeal",
    79: "ExecuteCommandEffectDamage",
    80: "ExecuteCommandEffectAbilityIncrease",
    81: "ExecuteCommandEffectDamageResistance",
    82: "ExecuteCommandEffectResurrection",
    83: "ExecuteCommandGetPlayerRestrictMode",
    84: "ExecuteCommandGetCasterLevel",
    85: "ExecuteCommandGetEffect",
    86: "ExecuteCommandGetEffect",
    87: "ExecuteCommandRemoveEffect",
    88: "ExecuteCommandGetIsEffectValid",
    89: "ExecuteCommandGetEffectDurationType",
    90: "ExecuteCommandGetEffectSubType",
    91: "ExecuteCommandGetEffectCreator",
    92: "ExecuteCommandIntToString",
    93: "ExecuteCommandGetObjectInArea",
    94: "ExecuteCommandGetObjectInArea",
    95: "ExecuteCommandRollDice",
    96: "ExecuteCommandRollDice",
    97: "ExecuteCommandRollDice",
    98: "ExecuteCommandRollDice",
    99: "ExecuteCommandRollDice",
    100: "ExecuteCommandRollDice",
    101: "ExecuteCommandRollDice",
    102: "ExecuteCommandRollDice",
    103: "ExecuteCommandRollDice",
    104: "ExecuteCommandVectorMagnitude",
    105: "ExecuteCommandGetMetaMagicFeat",
    106: "ExecuteCommandGetObjectType",
    107: "ExecuteCommandGetRacialType",
    108: "ExecuteCommandSavingThrow",
    109: "ExecuteCommandSavingThrow",
    110: "ExecuteCommandSavingThrow",
    111: "ExecuteCommandGetSpellSaveDC",
    112: "ExecuteCommandSetSubType",
    113: "ExecuteCommandSetSubType",
    114: "ExecuteCommandSetSubType",
    115: "ExecuteCommandEffectACIncrease",
    116: "ExecuteCommandGetAC",
    117: "ExecuteCommandEffectSavingThrowIncrease",
    118: "ExecuteCommandEffectAttackIncrease",
    119: "ExecuteCommandEffectDamageReduction",
    120: "ExecuteCommandEffectDamageIncrease",
    121: "ExecuteCommandTimeConversions",
    122: "ExecuteCommandTimeConversions",
    123: "ExecuteCommandTimeConversions",
    124: "ExecuteCommandSoundObjectSetFixedVariance",
    125: "ExecuteCommandGetAlignment",
    126: "ExecuteCommandGetPartyMemberCount",
    127: "ExecuteCommandGetAlignment",
    128: "ExecuteCommandGetObjectInShape",
    129: "ExecuteCommandGetObjectInShape",
    130: "ExecuteCommandEffectComplex",
    131: "ExecuteCommandSignalEvent",
    132: "ExecuteCommandEventUserDefined",
    133: "ExecuteCommandEffectComplex",
    134: "ExecuteCommandEffectComplex",
    135: "ExecuteCommandActionExchangeItem",
    136: "ExecuteCommandActionExchangeItem",
    137: "ExecuteCommandVectorNormalize",
    138: "ExecuteCommandGetItemStackSize",
    139: "ExecuteCommandGetAbilityScore",
    140: "ExecuteCommandGetIsDead",
    141: "ExecuteCommandPrintVector",
    142: "ExecuteCommandVector",
    143: "ExecuteCommandSetFacing",
    144: "ExecuteCommandVectorConversions",
    145: "ExecuteCommandVectorConversions",
    146: "ExecuteCommandDoTouchAttack",
    147: "ExecuteCommandDoTouchAttack",
    148: "ExecuteCommandEffectComplex",
    149: "ExecuteCommandEffectSpellImmunity",
    150: "ExecuteCommandSetItemStackSize",
    151: "ExecuteCommandGetDistanceBetween",
    152: "ExecuteCommandSetReturnStrref",
    153: "ExecuteCommandEffectForceJump",
    154: "ExecuteCommandEffectComplex",
    155: "ExecuteCommandGetItemInSlot",
    156: "ExecuteCommandEffectTemporaryForcePoints",
    157: "ExecuteCommandEffectComplex",
    158: "ExecuteCommandEffectComplex",
    159: "ExecuteCommandEffectChoke",
    160: "ExecuteCommandSetGlobalString",
    161: "ExecuteCommandEffectComplex",
    162: "ExecuteCommandSetCommandable",
    163: "ExecuteCommandGetCommandable",
    164: "ExecuteCommandEffectComplex",
    165: "ExecuteCommandEffectMovementSpeedIncrease",
    166: "ExecuteCommandGetHitDice",
    167: "ExecuteCommandActionFollowObject",
    168: "ExecuteCommandGetTag",
    169: "ExecuteCommandResistSpell",
    170: "ExecuteCommandGetEffectType",
    171: "ExecuteCommandEffectAreaEffect",
    172: "ExecuteCommandGetFactionEqual",
    173: "ExecuteCommandChangeFaction",
    174: "ExecuteCommandGetIsListening",
    175: "ExecuteCommandSetListening",
    176: "ExecuteCommandSetListenString",
    177: "ExecuteCommandTestString",
    178: "ExecuteCommandGetMatchedString",
    179: "ExecuteCommandGetMatchedStringsCount",
    180: "ExecuteCommandEffectVisualEffect",
    181: "ExecuteCommandGetFactionWeakestMember",
    182: "ExecuteCommandGetFactionStrongestMember",
    183: "ExecuteCommandGetFactionMostDamagedMember",
    184: "ExecuteCommandGetFactionLeastDamagedMember",
    185: "ExecuteCommandGetFactionGold",
    186: "ExecuteCommandGetFactionAverageReputation",
    187: "ExecuteCommandGetFactionAverageGoodEvilAlignment",
    188: "ExecuteCommandSoundObjectGetFixedVariance",
    189: "ExecuteCommandGetFactionAverageLevel",
    190: "ExecuteCommandGetFactionAverageXP",
    191: "ExecuteCommandGetFactionMostFrequentClass",
    192: "ExecuteCommandGetFactionWorstAC",
    193: "ExecuteCommandGetFactionBestAC",
    194: "ExecuteCommandGetGlobalString",
    195: "ExecuteCommandGetListenPatternNumber",
    196: "ExecuteCommandActionJumpToObject",
    197: "ExecuteCommandGetWaypointByTag",
    198: "ExecuteCommandGetTransitionTarget",
    199: "ExecuteCommandEffectLinkEffects",
    200: "ExecuteCommandGetObjectByTag",
    201: "ExecuteCommandAdjustAlignment",
    202: "ExecuteCommandActionWait",
    203: "ExecuteCommandSetAreaTransitionBMP",
    204: "ExecuteCommandActionStartConversation",
    205: "ExecuteCommandActionPauseConversation",
    206: "ExecuteCommandActionResumeConversation",
    207: "ExecuteCommandEffectBeam",
    208: "ExecuteCommandGetReputation",
    209: "ExecuteCommandAdjustReputation",
    210: "ExecuteCommandGetModuleName",
    211: "ExecuteCommandGetGoingToBeAttackedBy",
    212: "ExecuteCommandEffectForceResistanceIncrease",
    213: "ExecuteCommandGetLocation",
    214: "ExecuteCommandActionJumpToPoint",
    215: "ExecuteCommandLocation",
    216: "ExecuteCommandApplyEffectAtLocation",
    217: "ExecuteCommandGetIsPC",
    218: "ExecuteCommandDistanceConversions",
    219: "ExecuteCommandDistanceConversions",
    220: "ExecuteCommandApplyEffectToObject",
    221: "ExecuteCommandSpeakString",
    222: "ExecuteCommandGetSpellTargetLocation",
    223: "ExecuteCommandLocationAccess",
    224: "ExecuteCommandEffectBodyFuel",
    225: "ExecuteCommandLocationAccess",
    226: "ExecuteCommandGetNearestObject",
    227: "ExecuteCommandGetNearestObject",
    228: "ExecuteCommandGetNearestObject",
    229: "ExecuteCommandGetNearestObject",
    230: "ExecuteCommandIntToFloat",
    231: "ExecuteCommandFloatToInt",
    232: "ExecuteCommandStringConversions",
    233: "ExecuteCommandStringConversions",
    234: "ExecuteCommandCastSpell",
    235: "ExecuteCommandGetEmotions",
    236: "ExecuteCommandGetEmotions",
    237: "ExecuteCommandGetEmotions",
    238: "ExecuteCommandGetPCSpeaker",
    239: "ExecuteCommandGetStringByStrRef",
    240: "ExecuteCommandActionSpeakStringByStrRef",
    241: "ExecuteCommandDestroyObject",
    242: "ExecuteCommandGetModule",
    243: "ExecuteCommandCreateObject",
    244: "ExecuteCommandEventSpellCastAt",
    245: "ExecuteCommandGetSpellCast",
    246: "ExecuteCommandGetSpellCast",
    247: "ExecuteCommandGetUserDefinedEventNumber",
    248: "ExecuteCommandGetSpellId",
    249: "ExecuteCommandRandomName",
    250: "ExecuteCommandEffectPoison",
    251: "ExecuteCommandGetLoadFromSaveGame",
    252: "ExecuteCommandEffectComplex",
    253: "ExecuteCommandGetName",
    254: "ExecuteCommandGetLastSpeaker",
    255: "ExecuteCommandBeginConversation",
    256: "ExecuteCommandGetLastPerceived",
    257: "ExecuteCommandGetLastPerception",
    258: "ExecuteCommandGetLastPerception",
    259: "ExecuteCommandGetLastPerception",
    260: "ExecuteCommandGetLastClosedBy",
    261: "ExecuteCommandGetLastPerception",
    262: "ExecuteCommandGetInPersistentObject",
    263: "ExecuteCommandGetInPersistentObject",
    264: "ExecuteCommandGetAreaOfEffectCreator",
    265: "ExecuteCommandShowLevelUpGUI",
    266: "ExecuteCommandSetItemNonEquippable",
    267: "ExecuteCommandGetButtonMashCheck",
    268: "ExecuteCommandSetButtonMashCheck",
    269: "ExecuteCommandEffectForcePushTargeted",
    270: "ExecuteCommandEffectComplex",
    271: "ExecuteCommandGiveItem",
    272: "ExecuteCommandObjectToString",
    273: "ExecuteCommandEffectImmunity",
    274: "ExecuteCommandGetIsImmune",
    275: "ExecuteCommandEffectDamageImmunityIncrease",
    276: "ExecuteCommandGetEncounterData",
    277: "ExecuteCommandSetEncounterData",
    278: "ExecuteCommandGetEncounterData",
    279: "ExecuteCommandSetEncounterData",
    280: "ExecuteCommandGetEncounterData",
    281: "ExecuteCommandSetEncounterData",
    282: "ExecuteCommandGetModuleItemStuff",
    283: "ExecuteCommandGetModuleItemStuff",
    284: "ExecuteCommandSetCustomToken",
    285: "ExecuteCommandGetHasFeat",
    286: "ExecuteCommandGetHasSkill",
    287: "ExecuteCommandActionUseFeat",
    288: "ExecuteCommandActionUseSkill",
    289: "ExecuteCommandGetObjectVisibility",
    290: "ExecuteCommandGetObjectVisibility",
    291: "ExecuteCommandModuleAccess",
    292: "ExecuteCommandGetModuleItemStuff",
    293: "ExecuteCommandGetModuleItemStuff",
    294: "ExecuteCommandActionDoCommand",
    295: "ExecuteCommandEventConversation",
    296: "ExecuteCommandSetEncounterData",
    297: "ExecuteCommandGetEncounterData",
    298: "ExecuteCommandGetDistanceBetweenLocations",
    299: "ExecuteCommandGetReflexAdjustedDamage",
    300: "ExecuteCommandPlayAnimation",
    301: "ExecuteCommandTalent",
    302: "ExecuteCommandTalent",
    303: "ExecuteCommandTalent",
    304: "ExecuteCommandGetHasSpellEffect",
    305: "ExecuteCommandGetEffectSpellId",
    306: "ExecuteCommandGetCreatureHasTalent",
    307: "ExecuteCommandGetCreatureTalent",
    308: "ExecuteCommandGetCreatureTalent",
    309: "ExecuteCommandActionUseTalent",
    310: "ExecuteCommandActionUseTalent",
    311: "ExecuteCommandGetGoldPieceValue",
    312: "ExecuteCommandGetIsPlayableRacialType",
    313: "ExecuteCommandActionJumpToPoint",
    314: "ExecuteCommandEffectTemporaryHitpoints",
    315: "ExecuteCommandGetSkillRank",
    316: "ExecuteCommandGetAttackTarget",
    317: "ExecuteCommandGetLastAttackType",
    318: "ExecuteCommandGetLastAttackMode",
    319: "ExecuteCommandGetDistanceBetween2D",
    320: "ExecuteCommandGetIsInCombat",
    322: "ExecuteCommandGiveGoldToCreature",
    323: "ExecuteCommandSetIsDestroyable",
    324: "ExecuteCommandSetLocked",
    325: "ExecuteCommandGetLocked",
    326: "ExecuteCommandGetEnteringObject",
    328: "ExecuteCommandGetLastWeaponUsed",
    329: "ExecuteCommandActionInteractObject",
    330: "ExecuteCommandGetLastUsedBy",
    331: "ExecuteCommandGetAbilityModifier",
    332: "ExecuteCommandGetIdentified",
    333: "ExecuteCommandSetIdentified",
    334: "ExecuteCommandGetDistanceBetweenLocations2D",
    335: "ExecuteCommandGetDistanceToObject2D",
    336: "ExecuteCommandGetBlockingDoor",
    337: "ExecuteCommandGetIsDoorActionPossible",
    338: "ExecuteCommandDoDoorAction",
    339: "ExecuteCommandGetItemInInventory",
    340: "ExecuteCommandGetItemInInventory",
    341: "ExecuteCommandGetClassInformation",
    342: "ExecuteCommandGetClassInformation",
    343: "ExecuteCommandGetClassInformation",
    344: "ExecuteCommandGetDamageDealtByType",
    345: "ExecuteCommandGetTotalDamageDealt",
    346: "ExecuteCommandGetLastDamager",
    347: "ExecuteCommandGetLastDisarmed",
    348: "ExecuteCommandGetLastDisturbed",
    349: "ExecuteCommandGetLastLocked",
    350: "ExecuteCommandGetLastUnlocked",
    351: "ExecuteCommandEffectSkillIncrease",
    352: "ExecuteCommandGetInventoryDisturbType",
    353: "ExecuteCommandGetInventoryDisturbItem",
    354: "ExecuteCommandShowUpgradeScreen",
    355: "ExecuteCommandVersusEffect",
    356: "ExecuteCommandVersusEffect",
    357: "ExecuteCommandVersusEffect",
    358: "ExecuteCommandGetGender",
    359: "ExecuteCommandGetIsTalentValid",
    360: "ExecuteCommandActionMoveAwayFromLocation",
    361: "ExecuteCommandGetAttemptedAttackTarget",
    362: "ExecuteCommandTalentAccess",
    363: "ExecuteCommandTalentAccess",
    364: "ExecuteCommandPlayPazaak",
    365: "ExecuteCommandGetLastPazaakResult",
    366: "ExecuteCommandDisplayFeedBackText",
    367: "ExecuteCommandAddJournalQuestEntry",
    368: "ExecuteCommandRemoveJournalQuestEntry",
    369: "ExecuteCommandGetJournalEntry",
    370: "ExecuteCommandPlayRumblePattern",
    371: "ExecuteCommandStopRumblePattern",
    372: "ExecuteCommandEffectDamageForcePoints",
    373: "ExecuteCommandEffectHealForcePoints",
    374: "ExecuteCommandSendMessageToPC",
    375: "ExecuteCommandGetAttemptedSpellTarget",
    376: "ExecuteCommandGetLastOpenedBy",
    377: "ExecuteCommandGetHasSpell",
    378: "ExecuteCommandOpenStore",
    379: "ExecuteCommandSurrenderToEnemies",
    380: "ExecuteCommandGetFactionMember",
    381: "ExecuteCommandGetFactionMember",
    382: "ExecuteCommandMoveToPoint",
    383: "ExecuteCommandMoveToObject",
    384: "ExecuteCommandGetJournalQuestExperience",
    385: "ExecuteCommandActionJumpToObject",
    386: "ExecuteCommandSetMapPinEnabled",
    387: "ExecuteCommandEffectHitPointChangeWhenDying",
    388: "ExecuteCommandPopUpGUIPanel",
    389: "ExecuteCommandAddMultiClass",
    390: "ExecuteCommandGetIsLinkImmune",
    391: "ExecuteCommandEffectDroidStun",
    392: "ExecuteCommandEffectForcePushed",
    393: "ExecuteCommandGiveXPToCreature",
    394: "ExecuteCommandSetXP",
    395: "ExecuteCommandGetXP",
    396: "ExecuteCommandIntToHexString",
    397: "ExecuteCommandGetBaseItemType",
    398: "ExecuteCommandGetItemHasItemProperty",
    399: "ExecuteCommandActionEquipMostDamagingMelee",
    400: "ExecuteCommandActionEquipMostDamagingRanged",
    401: "ExecuteCommandGetItemACValue",
    402: "ExecuteCommandEffectComplex",
    404: "ExecuteCommandActionEquipMostEffectiveArmor",
    405: "ExecuteCommandGetIsDay",
    406: "ExecuteCommandGetIsNight",
    407: "ExecuteCommandGetIsDawn",
    408: "ExecuteCommandGetIsDusk",
    409: "ExecuteCommandGetIsEncounterCreature",
    410: "ExecuteCommandModuleAccess",
    411: "ExecuteCommandModuleAccess",
    412: "ExecuteCommandChangeFaction",
    413: "ExecuteCommandSoundObjectPlay",
    414: "ExecuteCommandSoundObjectStop",
    415: "ExecuteCommandSoundObjectSetVolume",
    416: "ExecuteCommandSoundObjectSetPosition",
    417: "ExecuteCommandSpeakOneLinerConversation",
    418: "ExecuteCommandGetGold",
    419: "ExecuteCommandModuleAccess",
    420: "ExecuteCommandEffectComplex",
    421: "ExecuteCommandSetLightsaberPowered",
    422: "ExecuteCommandGetIsWeaponEffective",
    423: "ExecuteCommandGetSpellCast",
    424: "ExecuteCommandEventActivateItem",
    425: "ExecuteCommandMusicBackground",
    426: "ExecuteCommandMusicBackground",
    427: "ExecuteCommandMusicBackground",
    428: "ExecuteCommandMusicBackground",
    429: "ExecuteCommandMusicBackground",
    430: "ExecuteCommandMusicBattle",
    431: "ExecuteCommandMusicBattle",
    432: "ExecuteCommandMusicBattle",
    433: "ExecuteCommandAmbientSound",
    434: "ExecuteCommandAmbientSound",
    435: "ExecuteCommandAmbientSound",
    436: "ExecuteCommandAmbientSound",
    437: "ExecuteCommandGetLastKiller",
    438: "ExecuteCommandGetSpellCastItem",
    439: "ExecuteCommandItemActivated",
    440: "ExecuteCommandItemActivated",
    441: "ExecuteCommandItemActivated",
    442: "ExecuteCommandItemActivated",
    443: "ExecuteCommandGetIsOpen",
    444: "ExecuteCommandTakeGoldFromCreature",
    445: "ExecuteCommandGetIsInConversation",
    446: "ExecuteCommandEffectAbilityDecrease",
    447: "ExecuteCommandEffectAttackDecrease",
    448: "ExecuteCommandEffectDamageDecrease",
    449: "ExecuteCommandEffectDamageImmunityDecrease",
    450: "ExecuteCommandEffectACDecrease",
    451: "ExecuteCommandEffectMovementSpeedDecrease",
    452: "ExecuteCommandEffectSavingThrowDecrease",
    453: "ExecuteCommandEffectSkillDecrease",
    454: "ExecuteCommandEffectForceResistanceDecrease",
    455: "ExecuteCommandGetPlotFlag",
    456: "ExecuteCommandSetPlotFlag",
    457: "ExecuteCommandEffectInvisibility",
    458: "ExecuteCommandEffectConcealment",
    459: "ExecuteCommandEffectForceShield",
    460: "ExecuteCommandEffectComplex",
    461: "ExecuteCommandSetDialogPlaceableCamera",
    462: "ExecuteCommandGetSoloMode",
    463: "ExecuteCommandEffectComplex",
    464: "ExecuteCommandGetMaxStealthXP",
    465: "ExecuteCommandEffectTrueSeeing",
    466: "ExecuteCommandEffectSeeInvisible",
    467: "ExecuteCommandEffectComplex",
    468: "ExecuteCommandSetMaxStealthXP",
    469: "ExecuteCommandEffectBlasterDeflectionIncrease",
    470: "ExecuteCommandEffectBlasterDeflectionDecrease",
    471: "ExecuteCommandEffectHorrified",
    472: "ExecuteCommandEffectSpellLevelAbsorption",
    473: "ExecuteCommandEffectComplex",
    474: "ExecuteCommandGetCurrentStealthXP",
    475: "ExecuteCommandGetNumStackedItems",
    476: "ExecuteCommandSurrenderToEnemies",
    477: "ExecuteCommandEffectMissChance",
    478: "ExecuteCommandSetCurrentStealthXP",
    479: "ExecuteCommandGetCreatureSize",
    480: "ExecuteCommandAwardStealthXP",
    481: "ExecuteCommandGetStealthXPEnabled",
    482: "ExecuteCommandSetStealthXPEnabled",
    483: "ExecuteCommandActionLockActions",
    484: "ExecuteCommandActionLockActions",
    485: "ExecuteCommandEffectModifyAttacks",
    486: "ExecuteCommandGetLastTrapDetected",
    487: "ExecuteCommandEffectDamageShield",
    488: "ExecuteCommandGetNearestMine",
    489: "ExecuteCommandGetAttemptedMovementTarget",
    490: "ExecuteCommandGetBlockingCreature",
    491: "ExecuteCommandGetFortitudeSavingThrow",
    492: "ExecuteCommandGetWillSavingThrow",
    493: "ExecuteCommandGetReflexSavingThrow",
    494: "ExecuteCommandGetChallengeRating",
    495: "ExecuteCommandGetFoundEnemyCreature",
    496: "ExecuteCommandGetMovementRate",
    497: "ExecuteCommandGetSubRace",
    498: "ExecuteCommandGetStealthXPDecrement",
    499: "ExecuteCommandSetStealthXPDecrement",
    500: "ExecuteCommandDuplicateHeadAppearance",
    501: "ExecuteCommandCastSpell",
    502: "ExecuteCommandCastSpell",
    503: "ExecuteCommandCutsceneAttack",
    504: "ExecuteCommandSetCameraMode",
    505: "ExecuteCommandSetLockOrientationInDialog",
    506: "ExecuteCommandSetLockHeadFollowInDialog",
    507: "ExecuteCommandCutsceneMove",
    508: "ExecuteCommandEnableVideoEffect",
    509: "ExecuteCommandStartNewModule",
    510: "ExecuteCommandDisableVideoEffect",
    511: "ExecuteCommandGetWeaponRanged",
    512: "ExecuteCommandDoSinglePlayerAutoSave",
    513: "ExecuteCommandGetGameDifficulty",
    514: "ExecuteCommandGetUserActionsPending",
    515: "ExecuteCommandRevealMap",
    516: "ExecuteCommandSetTutorialWindowsEnabled",
    517: "ExecuteCommandShowTutorialWindow",
    518: "ExecuteCommandStartCreditSequence",
    519: "ExecuteCommandIsCreditSequenceInProgress",
    522: "ExecuteCommandGetCurrentAction",
    523: "ExecuteCommandGetDifficultyModifier",
    524: "ExecuteCommandGetAppearanceType",
    525: "ExecuteCommandFloatingText",
    526: "ExecuteCommandFloatingText",
    527: "ExecuteCommandGetMineInfo",
    528: "ExecuteCommandGetMineInfo",
    529: "ExecuteCommandGetMineInfo",
    530: "ExecuteCommandGetMineInfo",
    531: "ExecuteCommandGetMineInfo",
    532: "ExecuteCommandGetMineInfo",
    533: "ExecuteCommandGetMineInfo",
    534: "ExecuteCommandGetMineInfo",
    535: "ExecuteCommandGetMineInfo",
    536: "ExecuteCommandGetMineInfo",
    537: "ExecuteCommandGetLockInfo",
    538: "ExecuteCommandGetLockInfo",
    539: "ExecuteCommandGetLockInfo",
    540: "ExecuteCommandGetLockInfo",
    541: "ExecuteCommandGetLockInfo",
    542: "ExecuteCommandGetPCLevellingUp",
    543: "ExecuteCommandGetHasFeatEffect",
    544: "ExecuteCommandSetPlaceableIllumination",
    545: "ExecuteCommandGetPlaceableIllumination",
    546: "ExecuteCommandGetIsDoorActionPossible",
    547: "ExecuteCommandDoDoorAction",
    548: "ExecuteCommandGetPC",
    549: "ExecuteCommandGetPC",
    550: "ExecuteCommandGetMineInfo",
    551: "ExecuteCommandGetIsTrapped",
    552: "ExecuteCommandSetEffectIcon",
    553: "ExecuteCommandFaceObjectAwayFromObject",
    554: "ExecuteCommandPopUpGUIPanel",
    555: "ExecuteCommandGetMineInfo",
    556: "ExecuteCommandGetLastHostileActor",
    557: "ExecuteCommandExportAllCharacters",
    558: "ExecuteCommandMusicBackgroundGetDayTrack",
    559: "ExecuteCommandMusicBackgroundGetNightTrack",
    560: "ExecuteCommandWriteTimestampedLogEntry",
    561: "ExecuteCommandGetModuleName",
    562: "ExecuteCommandGetFactionLeader",
    563: "ExecuteCommandSWMG_SetSpeedBlurEffect",
    564: "ExecuteCommandEndGame",
    565: "ExecuteCommandGetRunScriptVar",
    566: "ExecuteCommandGetCreatureMovmentType",
    567: "ExecuteCommandAmbientSound",
    568: "ExecuteCommandAmbientSound",
    569: "ExecuteCommandMusicBackgroundGetBattleTrack",
    570: "ExecuteCommandGetHasInventory",
    571: "ExecuteCommandGetStrRefSoundDuration",
    572: "ExecuteCommandAddToParty",
    573: "ExecuteCommandRemoveFromParty",
    574: "ExecuteCommandAddPartyMember",
    575: "ExecuteCommandRemovePartyMember",
    576: "ExecuteCommandIsObjectPartyMember",
    577: "ExecuteCommandGetPartyMemberByIndex",
    578: "ExecuteCommandGetGlobalNumber",
    579: "ExecuteCommandSetGlobalNumber",
    580: "ExecuteCommandGetGlobalNumber",
    581: "ExecuteCommandSetGlobalNumber",
    669: "ExecuteCommandAddJournalWorldEntry",
    670: "ExecuteCommandAddJournalWorldEntryStrref",
    671: "ExecuteCommandBarkString",
    672: "ExecuteCommandDeleteJournalWorldAllEntries",
    673: "ExecuteCommandDeleteJournalWorldEntry",
    674: "ExecuteCommandDeleteJournalWorldEntryStrref",
    675: "ExecuteCommandEffectForceDrain",
    676: "ExecuteCommandEffectPsychicStatic",
    677: "ExecuteCommandPlayVisualAreaEffect",
    678: "ExecuteCommandSetJournalQuestEntryPicture",
    679: "ExecuteCommandGetLocalValue",
    680: "ExecuteCommandSetLocalValue",
    681: "ExecuteCommandGetLocalValue",
    682: "ExecuteCommandSetLocalValue",
    689: "ExecuteCommandSoundObjectGetPitchVariance",
    690: "ExecuteCommandSoundObjectSetPitchVariation",
    691: "ExecuteCommandSoundObjectGetVolume",
    692: "ExecuteCommandGetGlobalLocation",
    693: "ExecuteCommandSetGlobalLocation",
    694: "ExecuteCommandAddAvailableNPCByObject",
    695: "ExecuteCommandRemoveAvailableNPC",
    696: "ExecuteCommandIsAvailableNPC",
    697: "ExecuteCommandAddAvailableNPCByTemplate",
    698: "ExecuteCommandSpawnAvailableNPC",
    699: "ExecuteCommandIsNPCPartyMember",
    700: "ExecuteCommandActionBarkString",
    701: "ExecuteCommandGetIsConversationActive",
    702: "ExecuteCommandEffectLightsaberThrow",
    703: "ExecuteCommandEffectWhirlWind",
    704: "ExecuteCommandGetPartyAIStyle",
    705: "ExecuteCommandGetNPCAIStyle",
    706: "ExecuteCommandSetPartyAIStyle",
    707: "ExecuteCommandSetNPCAIStyle",
    708: "ExecuteCommandSetNPCSelectability",
    709: "ExecuteCommandIsAvailableNPC",
    710: "ExecuteCommandClearAllEffects",
    711: "ExecuteCommandGetLastConversation",
    712: "ExecuteCommandShowPartySelectionGUI",
    713: "ExecuteCommandGetStandardFaction",
    714: "ExecuteCommandGivePlotXP",
    715: "ExecuteCommandGetMinOneHP",
    716: "ExecuteCommandSetMinOneHP",
    719: "ExecuteCommandSetGlobalFadeIn",
    720: "ExecuteCommandSetGlobalFadeOut",
    721: "ExecuteCommandGetLastHostileTarget",
    722: "ExecuteCommandGetLastAttackAction",
    723: "ExecuteCommandGetLastForcePowerUsed",
    724: "ExecuteCommandGetLastCombatFeatUsed",
    725: "ExecuteCommandGetLastAttackResult",
    726: "ExecuteCommandGetWasForcePowerSuccessful",
    727: "ExecuteCommandGetAttacker",
    728: "ExecuteCommandGetAttacker",
    729: "ExecuteCommandSetFormation",
    730: "ExecuteCommandActionFollowLeader",
    731: "ExecuteCommandSetForcePowerUnsuccessful",
    732: "ExecuteCommandGetIsDebilitated",
    733: "ExecuteCommandPlayMovie",
    734: "ExecuteCommandSaveNPCState",
    735: "ExecuteCommandTalentAccess",
    736: "ExecuteCommandChangeByFaction",
    737: "ExecuteCommandChangeByFaction",
    738: "ExecuteCommandPlayRoomAnimation",
    739: "ExecuteCommandShowGalaxyMap",
    740: "ExecuteCommandSetGalaxyMapPlanetSelectable",
    741: "ExecuteCommandGetGalaxyMapPlanetSelectable",
    742: "ExecuteCommandSetGalaxyMapPlanetAvailable",
    743: "ExecuteCommandGetGalaxyMapPlanetAvailable",
    744: "ExecuteCommandGetSelectedPlanet",
    745: "ExecuteCommandSoundObjectFadeAndStop",
    746: "ExecuteCommandSetAreaFogColor",
    747: "ExecuteCommandChangeItemCost",
    748: "ExecuteCommandGetIsLiveContentAvailable",
    749: "ExecuteCommandResetDialogState",
    750: "ExecuteCommandSetGoodEvilValue",
    751: "ExecuteCommandGetIsPoisoned",
    752: "ExecuteCommandGetSpellTarget",
    753: "ExecuteCommandSetSoloMode",
    754: "ExecuteCommandEffectComplex",
    755: "ExecuteCommandEffectComplex",
    756: "ExecuteCommandEffectComplex",
    757: "ExecuteCommandCancelPostDialogCharacterSwitch",
    758: "ExecuteCommandSetMaxHitPoints",
    759: "ExecuteCommandNoClicksFor",
    760: "ExecuteCommandHoldWorldFadeInForDialog",
    761: "ExecuteCommandShipBuild",
    762: "ExecuteCommandSurrenderToEnemies",
    763: "ExecuteCommandSuppressStatusSummaryEntry",
    764: "ExecuteCommandGetCheatCode",
    765: "ExecuteCommandSetMusicVolume",
    766: "ExecuteCommandCreateItemOnFloor",
    767: "ExecuteCommandSetAvailableNPCId",
    768: "ExecuteCommandIsMoviePlaying",
    769: "ExecuteCommandQueueMovie",
    770: "ExecuteCommandPlayMovieQueue",
    771: "ExecuteCommandYavinHackCloseDoor",
}

# Phase 3: Cross-reference and build renames
renames = {}  # tsl_fun_addr_str -> new_name
skipped_already_named = 0
skipped_no_k1_match = 0

for handler, cmd_ids in tsl_handler_to_ids.items():
    if not handler.startswith("FUN_"):
        skipped_already_named += 1
        continue

    addr_str = handler[4:]  # e.g. "0077f0b0"

    # Find K1 name for any of these cmd_ids
    k1_name = None
    for cid in sorted(cmd_ids):
        if cid in k1:
            candidate = k1[cid]
            if candidate.startswith("return_zero"):
                continue
            k1_name = candidate
            break

    if k1_name is None:
        skipped_no_k1_match += 1
        continue

    renames[addr_str] = k1_name

# Phase 4: Execute renames
program = currentProgram
txn = program.startTransaction("Bulk rename ExecuteCommand handlers from K1 command ID mapping")
renamed_count = 0
rename_errors = []
try:
    for addr_str, new_name in sorted(renames.items()):
        addr = af.getAddress("0x" + addr_str)
        func = fm.getFunctionAt(addr)
        if func is None:
            rename_errors.append("No function at 0x%s" % addr_str)
            continue

        if not func.getName().startswith("FUN_"):
            skipped_already_named += 1
            continue

        try:
            func.setName(new_name, SourceType.USER_DEFINED)
            renamed_count += 1
        except Exception:
            # Name conflict - try with address suffix
            try:
                func.setName("%s_%s" % (new_name, addr_str), SourceType.USER_DEFINED)
                renamed_count += 1
            except Exception as e2:
                rename_errors.append("Failed 0x%s -> %s: %s" % (addr_str, new_name, str(e2)))

    program.endTransaction(txn, True)
except Exception:
    program.endTransaction(txn, False)

# Output summary
output = ["BULK RENAME RESULTS:"]
output.append("  Renamed: %d" % renamed_count)
output.append("  Skipped (already named): %d" % skipped_already_named)
output.append("  Skipped (no K1 match): %d" % skipped_no_k1_match)
output.append("  Errors: %d" % len(rename_errors))
if rename_errors:
    output.append("\nErrors:")
    for err in rename_errors[:20]:
        output.append("  " + err)

__result__ = "\n".join(output)
