<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <StrideCompilerSkipBuild>true</StrideCompilerSkipBuild>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Net48Stub.cs" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-windows'">
    <PackageReference Include="Stride.Engine" Version="4.2.1.2487" />
    <PackageReference Include="Stride.Graphics" Version="4.2.1.2487" />
    <PackageReference Include="Stride.Input" Version="4.2.1.2487" />
    <PackageReference Include="Stride.CommunityToolkit.Windows" Version="1.0.0-preview.61" />
  </ItemGroup>
</Project>
